
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class cadastro extends javax.swing.JFrame {
    ArrayList<Tecnico> listaTec=new ArrayList();
    ArrayList<Aluno> listaAlu=new ArrayList();
    ArrayList<Funcionario> listaFun=new ArrayList();
    ArrayList<Professor> listaPro=new ArrayList();
    ArrayList<Curso> listaCurso = new ArrayList();
    ArrayList<Diciplinas> listaDic = new ArrayList();
    private String nomep;
    private String enderecop;
    private String telefonep;
    private String cpfp;
    private String ctpsp;
    private double salariop;

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    public cadastro(ArrayList<Aluno> listaAluno, ArrayList<Tecnico> listaTecn, 
    ArrayList<Funcionario> listaFunci, ArrayList<Professor> listaProf,
    ArrayList<Curso> listaCursos,ArrayList<Diciplinas> listaDici) {
        initComponents();
        listaAlu=listaAluno;
        listaTec=listaTecn;
        listaFun=listaFunci;
        listaPro=listaProf;
        listaCurso=listaCursos;
        listaDic=listaDici;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNome = new javax.swing.JLabel();
        LabelEndereco = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        LabelCPF = new javax.swing.JLabel();
        LabelCTPS = new javax.swing.JLabel();
        LabelSalario = new javax.swing.JLabel();
        box2 = new javax.swing.JCheckBox();
        finalizar = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        cpf = new javax.swing.JTextField();
        ctps = new javax.swing.JTextField();
        salario = new javax.swing.JTextField();
        LabelMensagen = new javax.swing.JLabel();
        box1 = new javax.swing.JCheckBox();
        box3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelNome.setText("nome");

        LabelEndereco.setText("Endereço");

        jLabelTelefone.setText("Telefone");

        LabelCPF.setText("Cpf");

        LabelCTPS.setText("Ctps");

        LabelSalario.setText("Salario");

        box2.setText("professor");
        box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCaixa2(evt);
            }
        });
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        finalizar.setText("cadastra");
        finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaFinalizar(evt);
            }
        });
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaNome(evt);
            }
        });

        endereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaEndereco(evt);
            }
        });

        telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaTelefone(evt);
            }
        });

        cpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCPF(evt);
            }
        });

        ctps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCTPS(evt);
            }
        });

        salario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaSalario(evt);
            }
        });

        LabelMensagen.setText("                                     qual função você exerce?");

        box1.setText("funcionario");
        box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCaixa1(evt);
            }
        });
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box3.setText("tecnico");
        box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCaixa3(evt);
            }
        });
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(LabelMensagen, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(finalizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCTPS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(endereco)
                            .addComponent(telefone)
                            .addComponent(cpf)
                            .addComponent(ctps)
                            .addComponent(salario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelNome)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEndereco)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCPF)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCTPS)
                    .addComponent(ctps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelSalario)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelMensagen)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box2)
                    .addComponent(box1)
                    .addComponent(box3))
                .addGap(18, 18, 18)
                .addComponent(finalizar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
        box2.setSelected(false);
        box3.setSelected(false);
    }//GEN-LAST:event_box1ActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
        box1.setSelected(false);
        box3.setSelected(false);
    }//GEN-LAST:event_box2ActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
          nomep=nome.getText();
          enderecop=endereco.getText();
          telefonep=telefone.getText();
          cpfp=cpf.getText();
          ctpsp=ctps.getText();
          salariop=Double.valueOf(salario.getText());
          
        if(box1.isSelected()==true || box2.isSelected()==true || box3.isSelected()==true){ 
            if(box1.isSelected()==true){
                Funcionario funcionario = new Funcionario();
                funcionario.setNome(nome.getText());
                funcionario.setCpf(cpf.getText());
                funcionario.setEndereco(endereco.getText());
                funcionario.setTelefone(telefone.getText());
                funcionario.setCtps(ctps.getText());
                funcionario.setSalario(Double.valueOf(salario.getText()));
                listaFun.add(funcionario);
                JOptionPane.showMessageDialog(null,"cadastro feito com sucesso");
                principal prin=new principal(listaAlu,listaTec,listaFun,listaPro,listaCurso,listaDic);
                prin.setLocationRelativeTo(null);
                prin.setVisible(true); 
                dispose();
            }
            if(box2.isSelected()==true){
                profe profer = new profe(nomep,cpfp,enderecop,telefonep,ctpsp,salariop,listaAlu,listaTec,listaFun,listaPro,listaCurso,listaDic);
                profer.setLocationRelativeTo(null);
                profer.setVisible(true); 
                dispose();
            }
            if(box3.isSelected()==true){
                tecnic tec= new tecnic(nomep,cpfp,enderecop,telefonep,ctpsp,salariop,listaAlu,listaTec,listaFun,listaPro,listaCurso,listaDic);
                tec.setLocationRelativeTo(null);
                tec.setVisible(true); 
                dispose();
            }
       }else{
           JOptionPane.showMessageDialog(null,"marque sua funcao");
       }
    }//GEN-LAST:event_finalizarActionPerformed

    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
        box1.setSelected(false);
        box2.setSelected(false);
    }//GEN-LAST:event_box3ActionPerformed

    private void mudaNome(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaNome
        // TODO add your handling code here:
        LabelEndereco.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelNome.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu nome");
    }//GEN-LAST:event_mudaNome

    private void mudaEndereco(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaEndereco
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelEndereco.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu endereço");
    }//GEN-LAST:event_mudaEndereco

    private void mudaTelefone(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaTelefone
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu telefone");
    }//GEN-LAST:event_mudaTelefone

    private void mudaCPF(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCPF
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelCPF.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu cpf");
    }//GEN-LAST:event_mudaCPF

    private void mudaCTPS(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCTPS
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelCTPS.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu Ctps");
    }//GEN-LAST:event_mudaCTPS

    private void mudaSalario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaSalario
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.red);
        LabelNome.setToolTipText("escreva seu endereço");
    }//GEN-LAST:event_mudaSalario

    private void mudaCaixa1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCaixa1
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelMensagen.setForeground(Color.red);
    }//GEN-LAST:event_mudaCaixa1

    private void mudaCaixa2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCaixa2
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelMensagen.setForeground(Color.red);
    }//GEN-LAST:event_mudaCaixa2

    private void mudaCaixa3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCaixa3
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelMensagen.setForeground(Color.red);
    }//GEN-LAST:event_mudaCaixa3

    private void mudaFinalizar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaFinalizar
        // TODO add your handling code here:
        LabelNome.setForeground(Color.black);
        jLabelTelefone.setForeground(Color.black);
        LabelCPF.setForeground(Color.black);
        LabelCTPS.setForeground(Color.black);
        LabelEndereco.setForeground(Color.black);
        LabelSalario.setForeground(Color.black);
        LabelMensagen.setForeground(Color.black);
    }//GEN-LAST:event_mudaFinalizar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCPF;
    private javax.swing.JLabel LabelCTPS;
    private javax.swing.JLabel LabelEndereco;
    private javax.swing.JLabel LabelMensagen;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelSalario;
    private javax.swing.JCheckBox box1;
    private javax.swing.JCheckBox box2;
    private javax.swing.JCheckBox box3;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField ctps;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
