
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cliente
 */
public class cadastroDiciplina extends javax.swing.JFrame {
    ArrayList<Tecnico> listaTec=new ArrayList();
    ArrayList<Aluno> listaAluno=new ArrayList();
    ArrayList<Funcionario> listaFunci=new ArrayList();
    ArrayList<Professor> listaPro=new ArrayList();
    ArrayList<Curso> listaCurso = new ArrayList();
    ArrayList<Diciplinas> listaDic = new ArrayList();
    /**
     * Creates new form cadastroDiciplina
     */
    public cadastroDiciplina() {
        initComponents();
    }

    public cadastroDiciplina(ArrayList<Aluno> listaAlu, ArrayList<Tecnico> listaTecn,
    ArrayList<Funcionario> listaFuncio, ArrayList<Professor> listaProf,
    ArrayList<Curso> listaCursos, ArrayList<Diciplinas> listaDici) {
        
        initComponents();
        listaAluno=listaAlu;
        listaTec=listaTecn;
        listaFunci=listaFuncio;
        listaPro=listaProf;
        listaCurso=listaCursos;
        listaDic=listaDici;
        mostraescolha();
        mostraCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoj = new javax.swing.JLabel();
        nomej = new javax.swing.JLabel();
        cargaj = new javax.swing.JLabel();
        professorj = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        carga = new javax.swing.JTextField();
        lista = new javax.swing.JComboBox<>();
        cadastra = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        cursoj = new javax.swing.JLabel();
        cursos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoj.setText("código");

        nomej.setText("nome");

        cargaj.setText("carga harária");

        professorj.setText("professor responsavel ");

        codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaC(evt);
            }
        });

        nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaN(evt);
            }
        });

        carga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCar(evt);
            }
        });

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolha um professor" }));
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaP(evt);
            }
        });
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        cadastra.setText("cadastra");
        cadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraActionPerformed(evt);
            }
        });

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        cursoj.setText("curso");

        cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "escolha um cuso" }));
        cursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mudaCurso(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cursoj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomej, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cargaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(professorj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigo)
                    .addComponent(nome)
                    .addComponent(carga)
                    .addComponent(lista, 0, 446, Short.MAX_VALUE)
                    .addComponent(cursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoj)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomej)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargaj)
                    .addComponent(carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(professorj)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cursoj)
                    .addComponent(cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastra)
                    .addComponent(voltar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraActionPerformed
        // TODO add your handling code here:
        if(lista.getSelectedItem().equals("escolha um professor") || cursos.getSelectedItem().equals("escolha um cuso")){
            JOptionPane.showMessageDialog(null, "escolha um professor ou um curso");
        }else{
            Diciplinas dic=new Diciplinas();
            dic.setCargaHoraria(Integer.valueOf(carga.getText()));
            dic.setCodigo(Integer.valueOf(codigo.getText()));
            dic.setNome(nome.getText());
            dic.setProfessor(pega((String) lista.getSelectedItem()));
            dic.setCurso(pegaCurso((String) cursos.getSelectedItem()));
            listaDic.add(dic);
            JOptionPane.showMessageDialog(null, "cadastrado");
            principal prin=new principal(listaAluno,listaTec,listaFunci,listaPro,listaCurso,listaDic);
            prin.setLocationRelativeTo(null);
            prin.setVisible(true); 
            dispose();
        }
    }//GEN-LAST:event_cadastraActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        principal prin=new principal(listaAluno,listaTec,listaFunci,listaPro,listaCurso,listaDic);
        prin.setLocationRelativeTo(null);
        prin.setVisible(true); 
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void mudaC(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaC
        // TODO add your handling code here:
        codigoj.setForeground(Color.red);
        nomej.setForeground(Color.black);
        cargaj.setForeground(Color.black);
        professorj.setForeground(Color.black);
        cursoj.setForeground(Color.black);
    }//GEN-LAST:event_mudaC

    private void mudaN(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaN
        // TODO add your handling code here:
        codigoj.setForeground(Color.black);
        nomej.setForeground(Color.red);
        cargaj.setForeground(Color.black);
        professorj.setForeground(Color.black);
        cursoj.setForeground(Color.black);
    }//GEN-LAST:event_mudaN

    private void mudaCar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCar
        // TODO add your handling code here:
        codigoj.setForeground(Color.black);
        nomej.setForeground(Color.black);
        cargaj.setForeground(Color.red);
        professorj.setForeground(Color.black);
        cursoj.setForeground(Color.black);
    }//GEN-LAST:event_mudaCar

    private void mudaP(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaP
        // TODO add your handling code here:
        codigoj.setForeground(Color.black);
        nomej.setForeground(Color.black);
        cargaj.setForeground(Color.black);
        professorj.setForeground(Color.red);
        cursoj.setForeground(Color.black);
    }//GEN-LAST:event_mudaP

    private void mudaCurso(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mudaCurso
        // TODO add your handling code here:
        codigoj.setForeground(Color.black);
        nomej.setForeground(Color.black);
        cargaj.setForeground(Color.black);
        professorj.setForeground(Color.black);
        cursoj.setForeground(Color.red);
    }//GEN-LAST:event_mudaCurso

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroDiciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cadastroDiciplina().setVisible(true);
        });
    }
    public void mostraescolha(){
        if(0<listaPro.size()){
            for(int i=0;i<listaPro.size();i++){
                lista.addItem(listaPro.get(i).getNome());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "não temos registros de prfessores");
        }
        }
    public void mostraCursos(){
        if(0<listaCurso.size()){
            for(int i=0;i<listaCurso.size();i++){
                cursos.addItem(listaCurso.get(i).getNome());
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "não temos registros de cusos");
        }
        }
    public Professor pega(String nome){
        for(int i=0;i<listaPro.size();i++){
            if(nome.equals(listaPro.get(i).getNome())){
                return listaPro.get(i);
            }
        }
        return null;
    }
    public Curso pegaCurso(String nome){
        for(int i=0;i<listaCurso.size();i++){
            if(nome.equals(listaCurso.get(i).getNome())){
                return listaCurso.get(i);
            }
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastra;
    private javax.swing.JTextField carga;
    private javax.swing.JLabel cargaj;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel codigoj;
    private javax.swing.JLabel cursoj;
    private javax.swing.JComboBox<String> cursos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel nomej;
    private javax.swing.JLabel professorj;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
